graph TD
  De[Deutschland]
  De --> Ewd[Einwanderung]
    Ewd --> Ebg[Einbürgerung]
      Ebg --> Ebgt[Einbürgerungstest]

  De --> Sp[Sprache]
    Sp --> A1
    Sp --> A2
    Sp --> B2
    Sp --> B1
    Sp --> C1
    Sp --> C2

  De --> Kt[Kultur]
    Kt --> KtFeh[Fernsehsendungen]
    Kt --> KtBcr[Bücher]
    Kt --> KtMus[Musik]
    Kt --> KtFil[Filme]
    Kt --> KtPod[Podcast]
    Kt --> KtYoutube[Youtube]
    Kt --> KtTwitch[Twitch]

  De --> Gsht[Gesundheit]
   Gsht --> VrsKvrs

  De --> Vrs[Versicherung]
    Vrs --> VrsKvrs[Krankenversicherung]
      VrsKvrs --> GKvrs[Gesetzliche]
      VrsKvrs --> PKvrs[Privat]

  De --> Wrs[Wirtschaft]
    Wrs --> Wrsl[Lohn]
      Wrsl --> Wrsls[Lohnsteuer]
    Wrs --> WrsIn[Investitionen]
      WrsIn --> WrsInP[Passiv]
        WrsInP --> WrsInPTg[Tagesgeld]
        WrsInP --> WrsInPFg[Festgeld]
      WrsIn --> WrsInA[Aktiv]
        WrsInA --> WrsInAA[Aktie]
        WrsInA --> WrsInAE[ETF]
        WrsInA --> WrsInAD[Dividende]

    Wrs --> WrsAv[Altersvorsorge]
      WrsAv --> WrsAvRn[Rente]
        WrsAvRn --> WrsRnRu[Rürup]
        WrsAvRn --> WrsRnRi[Riester]

  De --> Whng[Wohnung]
    Whng --> WhngMt[Mieten]
    Whng --> WhngKf[Kaufen]
      WhngKf --> WhngNk[Nebenkosten]

  De --> Vk[Verkehr]
    Vk --> VkA[Autos]
      VkA --> VkAF[Führerschein]
        VkAF --> VkAFU[Umschreibung]
        VkAF --> VkAFP[Führerscheinprüfung]
          VkAFP --> VkAFPV[Vorbereitung]
          VkAFP --> VkAFPT[Theoretische Führerscheinprüfung]
          VkAFP --> VkAFPP[Praktische Führerscheinprüfung]

      VkA --> VkAB[Besitzen]
        VkAB --> VkAL[Leasen]
        VkAB --> VkAK[Kaufen]
          VkAK --> VkAKF[Finanzierung]
          VkAK --> VkAKV[Versicherung]
          VkAK --> VkAKH[Hauptuntersuchung]
