graph TD
  De[Deutschland]
  De --> Ewd[Einwanderung]
    Ewd --> Ebg[Einbürgerung]
      Ebg --> Ebgt[Einbürgerungstest]

  De --> Sp[Sprache]
    Sp --> A1
    Sp --> A2
    Sp --> B2
    Sp --> B1
    Sp --> C1
    Sp --> C2

  De --> Kt[Kultur]
    Kt --> KtFeh[Fernsehsendungen]
    Kt --> KtBcr[Bücher]
    Kt --> KtMus[Musik]
    Kt --> KtFil[Filme]
    Kt --> KtPod[Podcast]
    Kt --> KtYoutube[Youtube]
    Kt --> KtTwitch[Twitch]

  De --> Gsht[Gesundheit]

  De --> Vrs[Versicherung]

  De --> Wrs[Wirtschaft]
    Wrs --> Wrsl[Lohn]
			Wrsl --> Wrsls[Lohnsteuer]
		Wrs --> WrsSp[Sparen]
		Wrs --> WrsRn[Rente]
			WrsRn --> WrsRnRu[Rürup]
			WrsRn --> WrsRnRi[Riester]

  De --> Whng[Wohnung]
    Whng --> WhngMt[Mieten]
    Whng --> WhngKf[Kaufen]
      WhngKf --> WhngNk[Nebenkosten]

  De --> Vk[Verkehr]
    Vk --> VkA[Autos]
      VkA --> VkAF[Führerschein]
        VkAF --> VkAFU[Umschreibung]
        VkAF --> VkAFP[Führerscheinprüfung]
          VkAFP --> VkAFPV[Vorbereitung]
          VkAFP --> VkAFPT[Theoretische Führerscheinprüfung]
          VkAFP --> VkAFPP[Praktische Führerscheinprüfung]

      VkA --> VkAK[Kaufen]
        VkAK --> VkAKF[Finanzierung]
        VkAK --> VkAKV[Versicherung]
        VkAK --> VkAKH[Hauptuntersuchung]
